### ISSUE TITLE
`getNewInheritance` method does not exist

### ISSUE THREAD

**Issue by beowulfenator** [rmrevin/yii2-rbac-migration#1]
Readme and docs mention `getNewInheritance`, but declaring that method doesn't do anything. Declaring `getInheritance` gets the job done, though.

**Comment by beowulfenator** [comment]
Oh, I see this extension is deprecated. Sorry.

**Comment by rmrevin** [comment]
Hello. Try other ext rmrevin/yii2-rbac-command https://github.com/rmrevin/yii2-rbac-command . Thanks.
